 -- ======================================= 
--     CREATE DATABASE AND SCHEMAS       =
-- =======================================

USE SYSADMIN;
 
-- DEV
CREATE DATABASE IF NOT EXISTS DEV_DB;
USE DATABASE DEV_DB;
CREATE SCHEMA IF NOT EXISTS DEMO_SCHEMA;
CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;
 
-- TST
CREATE DATABASE IF NOT EXISTS TST_DB;
USE DATABASE TST_DB;
CREATE SCHEMA IF NOT EXISTS DEMO_SCHEMA;
CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;
 
-- ======================================= 
--        CONNECT SNOWFLAKE TO GIT       =
-- =======================================
 
USE DATABASE DEV_DB;
USE SCHEMA DEMO_SCHEMA;
 
CREATE OR REPLACE SECRET DEMO_GITHUB_SECRET
	TYPE = PASSWORD
	USERNAME = ''   -- CHANGE THIS
	PASSWORD = '';  -- CHANGE THIS
 
 
CREATE OR REPLACE API INTEGRATION DEMO_GITHUB_API_INTEGRATION
	API_PROVIDER = GIT_HTTPS_API
	API_ALLOWED_PREFIXES = ('https://github.com/{your_account}') -- CHANGE THIS
	ALLOWED_AUTHENTICATION_SECRETS = (DEMO_GITHUB_SECRET)
	ENABLED = TRUE;
 
CREATE OR REPLACE GIT REPOSITORY DEMO_SNOWFLAKE_REPO
	API_INTEGRATION = DEMO_GITHUB_API_INTEGRATION
	GIT_CREDENTIALS = DEMO_GITHUB_SECRET
	ORIGIN = 'https://github.com/{your_account}/{your_repo}.git'; -- CHANGE THIS
 
SHOW GIT REPOSITORIES;
 
DESCRIBE GIT REPOSITORY DEMO_SNOWFLAKE_REPO;
 
-- ======================================= 
--    CREATE SF OBJECTS FOR DEPLOYMENT   =
-- =======================================
 
-- 1. CREATE ROLE
USE ROLE SECURITYADMIN;
CREATE ROLE "DEMO - DEPLOY";
 
-- 2. CREATE USER
USE ROLE SECURITYADMIN;
CREATE USER sa_deploy
PASSWORD = 'demo_sa_deploy'
DEFAULT_ROLE = "DEMO - DEPLOY";
 
-- 3. CREATE WAREHOUSE
USE ROLE SYSADMIN;
CREATE OR REPLACE WAREHOUSE POC_DEPLOYMENT_WH
COMMENT = 'For deployment purposes' 
WAREHOUSE_SIZE = 'Small'
WAREHOUSE_TYPE = 'STANDARD'
AUTO_RESUME = true
AUTO_SUSPEND = 60
MIN_CLUSTER_COUNT = 1 
MAX_CLUSTER_COUNT = 1 ;
 
-- 4. GRANT PRIVILEGES
 
USE ROLE SECURITYADMIN;
 
-- GENERAL
GRANT ROLE "DEMO - DEPLOY" TO USER sa_deploy;
GRANT ROLE "DEMO - DEPLOY" TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE POC_DEPLOYMENT_WH TO ROLE "DEMO - DEPLOY";
 
-- DEV_DB
GRANT USAGE ON DATABASE DEV_DB TO ROLE "DEMO - DEPLOY";
GRANT USAGE ON ALL SCHEMAS IN DATABASE DEV_DB TO ROLE "DEMO - DEPLOY";
GRANT ALL ON ALL SCHEMAS IN DATABASE DEV_DB TO ROLE "DEMO - DEPLOY";     -- CURRENT
GRANT ALL ON ALL TABLES IN DATABASE DEV_DB TO ROLE "DEMO - DEPLOY";      -- CURRENT
GRANT ALL ON ALL VIEWS IN DATABASE DEV_DB TO ROLE "DEMO - DEPLOY";       -- CURRENT
GRANT ALL ON FUTURE SCHEMAS IN DATABASE DEV_DB TO ROLE "DEMO - DEPLOY";  -- FUTURE
GRANT ALL ON FUTURE TABLES IN DATABASE DEV_DB TO ROLE "DEMO - DEPLOY";   -- FUTURE
GRANT ALL ON FUTURE VIEWS IN DATABASE DEV_DB TO ROLE "DEMO - DEPLOY";    -- FUTURE
 
-- TST_DB
GRANT USAGE ON DATABASE TST_DB TO ROLE "DEMO - DEPLOY";
GRANT USAGE ON ALL SCHEMAS IN DATABASE TST_DB TO ROLE "DEMO - DEPLOY";
GRANT ALL ON ALL SCHEMAS IN DATABASE TST_DB TO ROLE "DEMO - DEPLOY";     -- CURRENT
GRANT ALL ON ALL TABLES IN DATABASE TST_DB TO ROLE "DEMO - DEPLOY";      -- CURRENT
GRANT ALL ON ALL VIEWS IN DATABASE TST_DB TO ROLE "DEMO - DEPLOY";       -- CURRENT
GRANT ALL ON FUTURE SCHEMAS IN DATABASE TST_DB TO ROLE "DEMO - DEPLOY";  -- FUTURE
GRANT ALL ON FUTURE TABLES IN DATABASE TST_DB TO ROLE "DEMO - DEPLOY";   -- FUTURE
GRANT ALL ON FUTURE VIEWS IN DATABASE TST_DB TO ROLE "DEMO - DEPLOY";    -- FUTURE
 
SHOW GRANTS TO ROLE "DEMO - DEPLOY";
 
-- REPO
USE ROLE SYSADMIN;
USE DATABASE DEV_DB;
USE SCHEMA DEMO_SCHEMA;
 
GRANT READ,WRITE ON GIT REPOSITORY DEMO_SNOWFLAKE_REPO TO ROLE "DEMO - DEPLOY"; 
GRANT USAGE ON SECRET DEMO_GITHUB_SECRET TO ROLE "DEMO - DEPLOY";
 
-- ======================================= 
--              CLEANUP                  =
-- =======================================
DROP ROLE "DEMO - DEPLOY";
DROP USER sa_deploy;
DROP WAREHOUSE POC_DEPLOYMENT_WH;
 
DROP SECRET DEMO_GITHUB_SECRET;
DROP API INTEGRATION DEMO_GITHUB_API_INTEGRATION;
DROP GIT REPOSITORY DEMO_SNOWFLAKE_REPO;
 
DROP DATABASE DEV_DB;
DROP DATABASE TST_DB;